Kickoff4Kids420/Kickoff4Kids420/Controllers/ActivityTransactionController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Kickoff4Kids420.Models;
using PagedList;
using PagedList.Mvc;


namespace Kickoff4Kids420.Controllers
{
    [RequireHttps]
    [Authorize]
    public class ActivityTransactionController : Controller
    {
        private Kickoff4KidsDb db = new Kickoff4KidsDb();

        //
        // GET: /ActivityTransaction/
        [Authorize(Roles = "Admin")]
        public ActionResult Index(string activityName, string sortOrder, string currentFilter, string searchString, int? page)
        {

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Student_Name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "Date_desc" : "Date";

            // for Drop down
            var ActivityNameList = new List<string>();
            var ActivityNameQry = from a in db.Activities
                                  orderby a.ActivityName
                                  select a.ActivityName;

            ActivityNameList.AddRange(ActivityNameQry.Distinct());
            ViewBag.activityName = new SelectList(ActivityNameList);
            //

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;

            }

            ViewBag.CurrentFilter = searchString;

            var activitytransaction = from a in db.ActivityTransactions.Include(a => a.UserProfiles).Include(a => a.Activity)
                                      select a;

            if (!String.IsNullOrEmpty(searchString))
            {
                activitytransaction = activitytransaction.Where(a => a.UserProfiles.UserName.ToUpper().Contains(searchString.ToUpper()));

            }
            // for dropdown filter
            if (!String.IsNullOrEmpty(activityName))
            {
                activitytransaction = activitytransaction.Where(x => x.Activity.ActivityName == activityName);
            }
            //
            switch (sortOrder)
            {
                case "Student_Name_desc":
                    activitytransaction = activitytransaction.OrderByDescending(a => a.UserProfiles.UserName);
                    break;
                case "Date":
                    activitytransaction = activitytransaction.OrderBy(a => a.ActivityDate);
                    break;
                case "Date_desc":
                    activitytransaction = activitytransaction.OrderByDescending(a => a.ActivityDate);
                    break;
                default:
                    activitytransaction = activitytransaction.OrderBy(a => a.UserProfiles.UserName);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);

            //
            //var activitytransactions = db.ActivityTransactions.Include(a => a.UserProfiles).Include(a => a.Activity);
            //return View(activitytransactions.ToList());
            return View(activitytransaction.ToPagedList(pageNumber, pageSize));
        }


        //
        // GET: /ActivityTransaction/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            //Mark, get all user names of students.
            var usernames = Roles.GetUsersInRole("Student");
            //Fetch all of these profiles.
            var studentUsers = db.UserProfiles
                 .Where(x => usernames.Contains(x.UserName)).ToList();
  
            ViewBag.UserId = new SelectList(studentUsers, "UserId", "UserName");
            ViewBag.ActivityId = new SelectList(db.Activities, "ActivityId", "ActivityName");
            return View();
        }

        //
        // POST: /ActivityTransaction/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int[] userId, int[] activityId, DateTime activityDate)
        {
            if (ModelState.IsValid)
            {
                foreach (int i in userId)
                {
                    UserProfile updUserProfile = db.UserProfiles.Find(i);
                    foreach (int x in activityId)
                    {
                        Activity act = db.Activities.Find(x);
                        int points = act.PointValue;
                        updUserProfile.PointTotal += points;
                        updUserProfile.CumulativePointTotal += points;
                        var activityTransaction = new ActivityTransaction
                        {
                            UserId = i,
                            ActivityDate = activityDate,
                            ActivityId = x
                        };
                        db.ActivityTransactions.Add(activityTransaction);
                        db.SaveChanges();
                    }
                }
                //Fetch User Profile
                //UserProfile updUserProfile = db.UserProfiles.Find(activitytransaction.UserId);
                //Fetch Activity
               // Activity act = db.Activities.Find(activitytransaction.ActivityId);
                //Fetch point value for completed activity
                //int points = act.PointValue;
                //Add Points
                //updUserProfile.PointTotal += points;
                //updUserProfile.CumulativePointTotal += points;

                //db.ActivityTransactions.Add(activitytransaction);
               // db.SaveChanges();
                
                //AddStudentPoints(updUserProfile, points);
                
                return RedirectToAction("Index");
            }
            var usernames = Roles.GetUsersInRole("Student");
            var studentUsers = db.UserProfiles
                 .Where(x => usernames.Contains(x.UserName)).ToList();
            ViewBag.UserId = new MultiSelectList(studentUsers, "UserId", "UserName");
            ViewBag.ActivityId = new MultiSelectList(db.Activities, "ActivityId", "ActivityName");
            return RedirectToAction("Index");
        }
        //public void AddStudentPoints(UserProfile user, int points)
        //{
        //    var stud = db.UserProfiles.FirstOrDefault(c => c.UserId == user.UserId);
        //    stud.PointTotal += points;
        //    db.SaveChanges();
        //}
        //public void SubtractStudentPoints(UserProfile user, int points)
        //{
        //    var stud = db.UserProfiles.FirstOrDefault(c => c.UserId == user.UserId);
        //    stud.PointTotal -= points;
        //    db.SaveChanges();
        //}
        //public void AddPoints(int userId, int activityId)
        //{
        //    UserProfile profile = db.UserProfiles.Find(userId);
        //    Activity activity = db.Activities.Find(activityId);
        //    profile.PointTotal += activity.PointValue;
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(profile).State = EntityState.Modified;
        //        db.SaveChanges();
        //    }

        //}
        //
        // GET: /ActivityTransaction/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id = 0)
        {
            ActivityTransaction activitytransaction = db.ActivityTransactions.Find(id);
            if (activitytransaction == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", activitytransaction.UserId);
            ViewBag.ActivityId = new SelectList(db.Activities, "ActivityId", "ActivityName", activitytransaction.ActivityId);
            return View(activitytransaction);
        }

        //
        // POST: /ActivityTransaction/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(ActivityTransaction activitytransaction)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activitytransaction).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", activitytransaction.UserId);
            ViewBag.ActivityId = new SelectList(db.Activities, "ActivityId", "ActivityName", activitytransaction.ActivityId);
            return View(activitytransaction);
        }

        //
        // GET: /ActivityTransaction/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id = 0)
        {
            ActivityTransaction activitytransaction = db.ActivityTransactions.Find(id);
            if (activitytransaction == null)
            {
                return HttpNotFound();
            }
            return View(activitytransaction);
        }

        //
        // POST: /ActivityTransaction/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ActivityTransaction activitytransaction = db.ActivityTransactions.Find(id);
            //Fetch User Profile
            UserProfile updUserProfile = db.UserProfiles.Find(activitytransaction.UserId);
            //Fetch Activity
            Activity act = db.Activities.Find(activitytransaction.ActivityId);
            //Fetch Points for that activity
            int points = act.PointValue;
            updUserProfile.PointTotal -= points;
            db.ActivityTransactions.Remove(activitytransaction);
            db.SaveChanges();
            
            return RedirectToAction("Index");
        }
        public ActionResult StudentActiviesResult([Bind(Prefix = "id")]int userId)
        {
            var student = db.UserProfiles.Find(userId);
            if (student != null)
            {

Kickoff4Kids420/Kickoff4Kids420/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Kickoff4Kids420.Models;
using PagedList;
using PagedList.Mvc;

namespace Kickoff4Kids420.Controllers
{
    [RequireHttps]
    [Authorize(Roles = "Admin")]
    public class UserController : Controller
    {
        private Kickoff4KidsDb db = new Kickoff4KidsDb();

        //
        // GET: /User/

        public ActionResult Index(string studentUser, string sortOrder, string currentFilter, string searchString, int? page)
        {

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Student_Name_desc" : "";
            ViewBag.PointSortParm = sortOrder == "Point" ? "Point_desc" : "Point";

            // for drop down filter
            var StudentList = new List<string>();
            var StudentListQry = from s in db.Schools
                                 orderby s.SchoolName
                                 select s.SchoolName;

            StudentList.AddRange(StudentListQry.Distinct());
            ViewBag.studentUser = new SelectList(StudentList);
            //
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;

            }

            ViewBag.CurrentFilter = searchString;

            var students = from s in db.UserProfiles.Include(s => s.Schools)
                           select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.UserName.ToUpper().Contains(searchString.ToUpper()));

            }
            // for dropdown filter
            if (!String.IsNullOrEmpty(studentUser))
            {
                students = students.Where(x => x.Schools.SchoolName == studentUser);
            }
            switch (sortOrder)
            {
                case "Student_Name_desc":
                    students = students.OrderByDescending(s => s.UserName);
                    break;
                case "Point":
                    students = students.OrderBy(s => s.PointTotal);
                    break;
                case "Point_desc":
                    students = students.OrderByDescending(s => s.PointTotal);
                    break;
                default:
                    students = students.OrderBy(s => s.UserName);
                    break;
            }

            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(students.ToPagedList(pageNumber, pageSize));

        }

        //
        // GET: /User/Details/5

        public ActionResult Details(int id = 0)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // GET: /User/Create

        public ActionResult Create()
        {
            ViewBag.SchoolId = new SelectList(db.Schools, "SchoolId", "SchoolName");
            return View();
        }

        //
        // POST: /User/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                db.UserProfiles.Add(userprofile);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.SchoolId = new SelectList(db.Schools, "SchoolId", "SchoolName", userprofile.SchoolId);
            return View(userprofile);
        }

        //
        // GET: /User/Edit/5

        public ActionResult Edit(int id = 0)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            ViewBag.SchoolId = new SelectList(db.Schools, "SchoolId", "SchoolName", userprofile.SchoolId);
            return View(userprofile);
        }

        //
        // POST: /User/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userprofile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SchoolId = new SelectList(db.Schools, "SchoolId", "SchoolName", userprofile.SchoolId);
            return View(userprofile);
        }

        //
        // GET: /User/Delete/5

        public ActionResult Delete(int id = 0)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // POST: /User/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            string[] rolesArray = Roles.GetRolesForUser(userprofile.UserName);
            Roles.RemoveUserFromRoles(userprofile.UserName, rolesArray);
            db.UserProfiles.Remove(userprofile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Kickoff4Kids420/Kickoff4Kids420/Views/ActivityTransaction/Create.cshtml
@using System.Collections
@model Kickoff4Kids420.Models.ActivityTransaction


@{
    ViewBag.Title = "Create";
}
<div class="breadcrumbs margin-bottom-40">
    <div class="container">
        <h1 class="pull-left">Create Activity Transaction</h1>
    </div>
</div>

<div class="container">
    <div class="panel panel-red">
        <div class="panel-heading">
            <h1 class="panel-title">New Activity Transaction</h1>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>

                    @Html.HiddenFor(model => model.UserProfiles)
                    <div class="editor-label">
                        @Html.LabelFor(model => model.UserId, "UserProfiles")
                    </div>
                    <div class="editor-field margin-bottom-10">
                        @Html.ListBox("UserId", (MultiSelectList)ViewBag.UserId)
                        @Html.ValidationMessageFor(model => model.UserId)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.ActivityDate)
                    </div>
                    <div class="editor-field margin-bottom-10">
                        <input class="text-box single-line" data-val="true" data-val-date="The field Activity Date must be a date." id="ActivityDate" name="ActivityDate" type="date" value="">
                        @Html.ValidationMessageFor(model => model.ActivityDate)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.ActivityId, "Activity")
                    </div>
                    <div class="editor-field margin-bottom-10">
                        @Html.ListBox("ActivityId", (MultiSelectList)ViewBag.ActivityId)
                        @Html.ValidationMessageFor(model => model.ActivityId)
                    </div>
                    <p>
                        <input class="btn-u btn-u-red" type="submit" value="Create" />
                    </p>
                </fieldset>
            }

            <div>
                @Html.ActionLink("Back to Completed Activities", "Index")
            </div>
        </div>
    </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kickoff4Kids420/Kickoff4Kids420/Views/ActivityTransaction/Delete.cshtml
@model Kickoff4Kids420.Models.ActivityTransaction

@{
    ViewBag.Title = "Delete";
}
<div class="breadcrumbs margin-bottom-40">
    <div class="container">
        <h1 class="pull-left">Delete Activity Transaction</h1>
    </div>
</div>
<div class="container">
    <div class="panel panel-red">
        <div class=" panel-heading">
            <h2 class="panel-title">Delete</h2>
        </div>
        <div class="panel-body">
            <h4>Are you sure you want to delete this Activity Transaction?</h4>
            <form role="form">
            <fieldset>
                <legend></legend>

                <div class="form-group">
                    <div class="display-label">
                        <strong> @Html.DisplayNameFor(model => model.UserProfiles.UserName)</strong>
                    </div>
                    <div class="display-field">
                        @Html.DisplayFor(model => model.UserProfiles.UserName)
                    </div>
               </div>

                <div class="form-group">
                    <div class="display-label">
                        <strong> @Html.DisplayNameFor(model => model.ActivityDate)</strong>
                                </div>
                                <div class="display-field">
                                    @Html.DisplayFor(model => model.ActivityDate)
                                            </div>
                                        </div>

                <div class="form-group">
                    <div class="display-label">
                        <strong>@Html.DisplayNameFor(model => model.Activity.ActivityName)</strong>
                                </div>
                                <div class="display-field">
                                    @Html.DisplayFor(model => model.Activity.ActivityName)
                                            </div>
                                        </div>
            </fieldset>
                </form>


            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <p>
                    <input class="btn-u btn-u-red" type="submit" value="Delete" />
                    </p>
                <p>
                    @Html.ActionLink("Back to Completed Activities", "Index")
                </p>
            }
        </div>
    </div>
</div>

Kickoff4Kids420/Kickoff4Kids420/Views/ActivityTransaction/Details.cshtml
@model Kickoff4Kids420.Models.ActivityTransaction

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>ActivityTransaction</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProfiles.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProfiles.UserName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ActivityDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ActivityDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Activity.ActivityName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Activity.ActivityName)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ActivityTransactionId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Kickoff4Kids420/Kickoff4Kids420/Views/ActivityTransaction/Edit.cshtml
@model Kickoff4Kids420.Models.ActivityTransaction

@{
    ViewBag.Title = "Edit";
}
<div class="breadcrumbs margin-bottom-40">
<div class="container">
    <h1 class="pull-left">Edit ActivityTransaction</h1>
</div>
</div>
<div class="container">
    <div class="panel panel-red">
        <div class="panel-heading">
            <h2 class="panel-title">ActivityTransaction</h2>
        </div>
        <div class="panel-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>

                    @Html.HiddenFor(model => model.ActivityTransactionId)

                    <div class="editor-label">
                        @Html.LabelFor(model => model.UserId, "UserProfiles")
                    </div>
                    <div class="editor-field margin-bottom-10">
                        @Html.DropDownList("UserId", String.Empty)
                        @Html.ValidationMessageFor(model => model.UserId)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.ActivityDate)
                    </div>
                    <div class="editor-field margin-bottom-10">
                        <input class="text-box single-line" data-val="true" data-val-date="The field Activity Date must be a date." id="ActivityDate" name="ActivityDate" type="date" value="">
                        @Html.ValidationMessageFor(model => model.ActivityDate)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.ActivityId, "Activity")
                    </div>
                    <div class="editor-field margin-bottom-10">
                        @Html.DropDownList("ActivityId", String.Empty)
                        @Html.ValidationMessageFor(model => model.ActivityId)
                    </div>

                    <p>
                        <input class="btn-u btn-u-red" type="submit" value="Save" />
                    </p>
                </fieldset>
            }

            <div>
                @Html.ActionLink("Back to Completed Activities", "Index")
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kickoff4Kids420/Kickoff4Kids420/Views/ActivityTransaction/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Kickoff4Kids420.Models.ActivityTransaction>

@{
    ViewBag.Title = "Index";
}

<div class="breadcrumbs margin-bottom-40">
    <div class="container">
        <h1 class="pull-left">Currently Available Activities</h1>
    </div>
</div>
<div class="container">
    <div class="panel panel-red">
        <div class="panel-heading">
            <h1 class="panel-title">Completed Activities</h1>
        </div>
        <br />
        @using (Html.BeginForm("Index", "ActivityTransaction", FormMethod.Get))
        {
            <ul class="list-inline">
                <li>
                    Activity: @Html.DropDownList("activityName", "All")
                <li />
                <li>
                    Search by Name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                    <input type="submit" value="Go!" />
                </li>
                <li>
                    @Html.ActionLink("Add New", "Create", null, new { @class = "btn-u btn-u" })
                </li>
            </ul>
        }

        <table class="table table-striped table-hover table-bordered">
            <tr>
                <th>
                    @Html.ActionLink("Student Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter, activityName = Request.QueryString["activityName"] })
                </th>
                <th>
                    @Html.ActionLink("Activity Date", "Index", new { sortOrder = ViewBag.DateSortParm, currentFilter = ViewBag.CurrentFilter, activityName = Request.QueryString["activityName"] })
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().Activity.ActivityName)
                </th>
                <th>
                    Points Earned
                </th>
                <th>
                    Modify
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserProfiles.UserName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ActivityDate)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Activity.ActivityName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Activity.PointValue)
                    </td>
                    <td class="text-right span2">
                        @Html.ActionLink(" ", "Edit", new { id = item.ActivityTransactionId }, new { @class = " icon icon-edit" }) |
                        @Html.ActionLink(" ", "Delete", new { id = item.ActivityTransactionId }, new { @class = " icon icon-trash" })
                    </td>
                </tr>
            }

        </table>
    </div>

</div>
<div class="text-center">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter, activityName = Request.QueryString["activityName"] }),
    new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true })
</div>

Kickoff4Kids420/Kickoff4Kids420/Views/ActivityTransaction/IndividualStudentActivity.cshtml
@model IEnumerable<Kickoff4Kids420.Models.ActivityTransaction>

@{
    ViewBag.Title = "Completed Activities";
}

<div class="breadcrumbs margin-bottom-40">
    <div class="container">
        <h1 class="pull-left">Completed Activities</h1>
    </div>
</div>
<div class="container">
    <div class="panel panel-red margin-bottom-40">
        <div class="panel-heading">
            <h1 class="panel-title">Activities Completed By @User.Identity.Name</h1>
        </div>
        <br />
        <table class="table table-bordered table-hover table-striped">
            <tr>
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                    @*
                        @Html.DisplayNameFor(model => model.LastName)
                    *@
                </th>
                <th>
                    Activity
                </th>
                <th>
                    Completion Date
                </th>
            </tr>

            @foreach (var item in Model.Where(item => item.UserProfiles.UserName.ToLower() == User.Identity.Name.ToLower()))
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserProfiles.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserProfiles.LastName)
                    <td>
                        @Html.DisplayFor(modelItem => item.Activity.ActivityName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ActivityDate)
                    </td>
                </tr>
            }

        </table>

    </div>
</div>

Kickoff4Kids420/Kickoff4Kids420/Views/ActivityTransaction/StudentActiviesResult.cshtml
@model Kickoff4Kids420.Models.UserProfile


@{
    ViewBag.Title = "Index";
}

<div class="container">
    <div class="panel panel-red">
        <div class="panel-heading">
            <h2 class="panel-title">Completed Activities for @Model.UserName</h2>
        </div>

        @Html.Partial("_Transactions", Model.ActivityTransactions)

        <p >
            @Html.ActionLink("Back to Students", "Index", "User")
        </p>
    </div>
</div>

Kickoff4Kids420/Kickoff4Kids420/Views/ActivityTransaction/_Transactions.cshtml
@model IEnumerable<Kickoff4Kids420.Models.ActivityTransaction>
<table class="table table-striped table-hover table-bordered">
    <tr>
        <th>
            Activity Name
        </th>
        <th>
            Activity Date
        </th>
        <th>
            Points Earned
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Activity.ActivityName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ActivityDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Activity.PointValue)
            </td>
            <td>
                @Html.ActionLink(" ", "Delete", new { id = item.ActivityTransactionId }, new { @class = "icon-trash" })
            </td>
        </tr>
    }

</table>