Kickoff4Kids420/Kickoff4Kids420/Models/Activity.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace Kickoff4Kids420.Models
{
    public class Activity
    {
        public int ActivityId { get; set; }
        [DisplayName("Activity Name")]
        public string ActivityName { get; set; }
        public string Description { get; set; }
        [DisplayName("Point Value")]
        public int PointValue { get; set; }
    }
}

Kickoff4Kids420/Kickoff4Kids420/Controllers/ActivityController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kickoff4Kids420.Models;
using PagedList;
using PagedList.Mvc;

namespace Kickoff4Kids420.Controllers
{
    [Authorize]
    public class ActivityController : Controller
    {
        private Kickoff4KidsDb db = new Kickoff4KidsDb();

        //
        // GET: /Activity/

        public ActionResult Index(string currentActivity, string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Activity_Name_desc" : "";
            ViewBag.PointSortParm = sortOrder == "Points" ? "Points_desc" : "Points";


            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;

            }

            ViewBag.CurrentFilter = searchString;

            var activities = from a in db.Activities
                             select a;

            if (!String.IsNullOrEmpty(searchString))
            {
                activities = activities.Where(a => a.ActivityName.ToUpper().Contains(searchString.ToUpper()));

            }
            switch (sortOrder)
            {
                case "Activity_Name_desc":
                    activities = activities.OrderByDescending(p => p.ActivityName);
                    break;
                case "Points":
                    activities = activities.OrderBy(p => p.PointValue);
                    break;
                case "Points_desc":
                    activities = activities.OrderByDescending(p => p.PointValue);
                    break;
                default:
                    activities = activities.OrderBy(p => p.ActivityName);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(activities.ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /Activity/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Activity/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Activities.Add(activity);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(activity);
        }

        //
        // GET: /Activity/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        //
        // POST: /Activity/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Activity activity)
        {
            if (ModelState.IsValid)
            {
                db.Entry(activity).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(activity);
        }

        //
        // GET: /Activity/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Activity activity = db.Activities.Find(id);
            if (activity == null)
            {
                return HttpNotFound();
            }
            return View(activity);
        }

        //
        // POST: /Activity/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Activity activity = db.Activities.Find(id);
            db.Activities.Remove(activity);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Kickoff4Kids420/Kickoff4Kids420/Views/Activity/Create.cshtml
@model Kickoff4Kids420.Models.Activity

@{
    ViewBag.Title = "Create";
}
<div class="breadcrumbs margin-bottom-40">
    <div class="container">
        <h1 class="pull-left">Create Activity</h1>
    </div>
</div>
<div class="container">
    <div class="panel panel-red">
        <div class="panel-heading">
            <h2 class="panel-title">New Activity</h2>
        </div>
        <div class=" panel-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.ActivityName)
                    </div>
                    <div class="editor-field margin-bottom-10">
                        @Html.EditorFor(model => model.ActivityName)
                        @Html.ValidationMessageFor(model => model.ActivityName)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.Description)
                    </div>
                    <div class="editor-field margin-bottom-10">
                        @Html.EditorFor(model => model.Description)
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.PointValue)
                    </div>
                    <div class="editor-field margin-bottom-10">
                        @Html.EditorFor(model => model.PointValue)
                        @Html.ValidationMessageFor(model => model.PointValue)
                    </div>

                    <p>
                        <input class="btn-u btn-u-red" type="submit" value="Create" />
                    </p>
                </fieldset>
            }

            <div>
                @Html.ActionLink("Back to Current Activities", "Index")
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kickoff4Kids420/Kickoff4Kids420/Views/Activity/Delete.cshtml
@model Kickoff4Kids420.Models.Activity

@{
    ViewBag.Title = "Delete";
}
<div class="breadcrumbs margin-bottom-40">
    <div class="container">
        <h1 class="pull-left">Delete Activity</h1>
    </div>
</div>
<div class="container">
    <div class="panel panel-red">
        <div class="panel-heading">
            <h2 class="panel-title">Delete</h2>
        </div>
        <div class=" panel-body">
            <h4>Are you sure you want to delete this Activity?</h4>
            <form role="form">
                <fieldset>

                    <legend></legend>
                    <div class=" form-group">
                        <div class="display-label">
                           <strong> @Html.DisplayNameFor(model => model.ActivityName)</strong>
                        </div>
                        <div class="display-field">
                            @Html.DisplayFor(model => model.ActivityName)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="display-label">
                          <strong>  @Html.DisplayNameFor(model => model.Description)</strong>
                        </div>
                        <div class="display-field">
                            @Html.DisplayFor(model => model.Description)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="display-label">
                           <strong> @Html.DisplayNameFor(model => model.PointValue)</strong>
                        </div>
                        <div class="display-field">
                            @Html.DisplayFor(model => model.PointValue)
                        </div>
                    </div>

                </fieldset>
            </form>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <p>
                    <input class="btn-u btn-u-red" type="submit" value="Delete" />
                </p>
                 <p>

                     @Html.ActionLink("Back to Current Activities", "Index")
                 </p>
            }
        </div>
    </div>
</div>

Kickoff4Kids420/Kickoff4Kids420/Views/Activity/Details.cshtml
@model Kickoff4Kids420.Models.Activity

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Activity</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ActivityName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ActivityName)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.PointValue)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.PointValue)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ActivityId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Kickoff4Kids420/Kickoff4Kids420/Views/Activity/Edit.cshtml
@model Kickoff4Kids420.Models.Activity

@{
    ViewBag.Title = "Edit";
}
<div class="breadcrumbs margin-bottom-40">
    <div class="container">
        <h1 class="pull-left">Edit Activity</h1>
    </div>
</div>
<div class=" container">
    <div class="panel panel-red">
        <div class="panel-heading">
            <h2 class="panel-title">Activity</h2>
        </div>

        <div class="panel-body">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)

                <fieldset>

                    @Html.HiddenFor(model => model.ActivityId)

                    <div class="editor-label">
                        @Html.LabelFor(model => model.ActivityName)
                    </div>
                    <div class="editor-field margin-bottom-10">
                        @Html.EditorFor(model => model.ActivityName)
                        @Html.ValidationMessageFor(model => model.ActivityName)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.Description)
                    </div>
                    <div class="editor-field margin-bottom-10">
                        @Html.EditorFor(model => model.Description)
                        @Html.ValidationMessageFor(model => model.Description)
                    </div>

                    <div class="editor-label">
                        @Html.LabelFor(model => model.PointValue)
                    </div>
                    <div class="editor-field margin-bottom-10">
                        @Html.EditorFor(model => model.PointValue)
                        @Html.ValidationMessageFor(model => model.PointValue)
                    </div>

                    <p>
                        <input class="btn-u btn-u-red" type="submit" value="Save" />
                    </p>
                </fieldset>
            }

            <div>
                @Html.ActionLink("Back to Current Activities", "Index")
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Kickoff4Kids420/Kickoff4Kids420/Views/Activity/Index.cshtml
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<Kickoff4Kids420.Models.Activity>

@{
    ViewBag.Title = "Index";
}
<div class="breadcrumbs margin-bottom-40">
    <div class="container">
        <h1 class="pull-left">Currently Eligible Activities</h1>
    </div>
</div>
<div class="container">
    <div class="panel panel-red">
        <div class="panel-heading">
            <h2 class="panel-title">Current Activities</h2>
        </div>
        <br />
        @using (Html.BeginForm("Index", "Activity", FormMethod.Get))
        {
            <ul class="list-inline">
                <li>
                    Search by Name: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
                    <input type="submit" value="Go!" />
                </li>
                <li>
                    @Html.ActionLink("Add Activity", "Create", null, new { @class = "btn-u btn-u" })
                </li>
            </ul>
        }

        <table class="table table-bordered table-hover table-striped">
            <tr>
                <th>
                    @Html.ActionLink("Activity Name", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })

                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().Description)
                </th>
                <th>
                    @Html.ActionLink("Point Value", "Index", new { sortOrder = ViewBag.PointSortParm, currentFilter = ViewBag.CurrentFilter })
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ActivityName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PointValue)
                    </td>
                    <td class="span2">
                        @Html.ActionLink(" ", "Edit", new { id = item.ActivityId }, new { @class = "icon-edit" }) |
                        @Html.ActionLink(" ", "Delete", new { id = item.ActivityId }, new { @class = "icon-trash" })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>
<div class="text-center">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }),
    new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded, DisplayPageCountAndCurrentLocation = true })
</div>