Kickoff4Kids420/Kickoff4Kids420/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kickoff4Kids420.Models;

namespace Kickoff4Kids420.Controllers
{
    [RequireHttps]
    [Authorize]
    
    public class HomeController : Controller
    {
        Kickoff4KidsDb db = new Kickoff4KidsDb();

        [AllowAnonymous]
        public ActionResult Index()
        {
            var fp = new FrontPage();
            fp = db.FrontPage.Find(1);           
            return View(fp);
            
            
        }
        public ActionResult About()  
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        [AllowAnonymous]
        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        [AllowAnonymous]
        public ActionResult Gallery()
        {

            return View();
        }

        [AllowAnonymous]
        public ActionResult Help()
        {
            return View();
        }
        [Authorize(Roles = "Admin")]
        public ActionResult AdminPanel()
        {
            return View();
        }
        [AllowAnonymous]
        public ActionResult Terms()
        {
            return View();
        }
        [AllowAnonymous]
        public ActionResult Privacy()
        {
            return View();
        }
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }



        
    }
}

Kickoff4Kids420/Kickoff4Kids420/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kickoff4Kids420.Models;
using PagedList;
using PagedList.Mvc;

namespace Kickoff4Kids420.Controllers
{
    [RequireHttps]
    
    public class OrderController : Controller
    {
        private Kickoff4KidsDb db = new Kickoff4KidsDb();

        //
        // GET: /Order/
        [Authorize(Roles = "Admin")]
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.FNameSortParm = String.IsNullOrEmpty(sortOrder) ? "First_Name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "OrderDate" ? "OrderDate_desc" : "OrderDate";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;

            }

            ViewBag.CurrentFilter = searchString;

            var orders = from o in db.Orders.Include(o => o.UserProfiles)
                         select o;

            if (!String.IsNullOrEmpty(searchString))
            {
                orders = orders.Where(p => p.FirstName.ToUpper().Contains(searchString.ToUpper()));

            }
            switch (sortOrder)
            {
                case "First_Name_desc":
                    orders = orders.OrderByDescending(o => o.FirstName);
                    break;
                case "OrderDate":
                    orders = orders.OrderBy(o => o.OrderDate);
                    break;
                case "OrderDate_desc":
                    orders = orders.OrderByDescending(o => o.OrderDate);
                    break;
                default:
                    orders = orders.OrderBy(o => o.FirstName);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(orders.ToPagedList(pageNumber, pageSize));


            //var orders = db.Orders.Include(o => o.UserProfiles);
            //return View(orders.ToList());
        }
        [Authorize(Roles = "Admin")]
        public ActionResult FulfilledOrders(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.FNameSortParm = String.IsNullOrEmpty(sortOrder) ? "First_Name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "OrderDate" ? "OrderDate_desc" : "OrderDate";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;

            }

            ViewBag.CurrentFilter = searchString;

            var orders = from o in db.Orders.Include(o => o.UserProfiles)
                         select o;

            if (!String.IsNullOrEmpty(searchString))
            {
                orders = orders.Where(p => p.FirstName.ToUpper().Contains(searchString.ToUpper()));

            }
            switch (sortOrder)
            {
                case "First_Name_desc":
                    orders = orders.OrderByDescending(o => o.FirstName);
                    break;
                case "OrderDate":
                    orders = orders.OrderBy(o => o.OrderDate);
                    break;
                case "OrderDate_desc":
                    orders = orders.OrderByDescending(o => o.OrderDate);
                    break;
                default:
                    orders = orders.OrderBy(o => o.FirstName);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(orders.ToPagedList(pageNumber, pageSize));
            //var orders = db.Orders.Include(o => o.UserProfiles);
            //return View(orders.ToList());
        }
        [Authorize(Roles = "Admin")]
        public ActionResult UnFulfilledOrders(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.FNameSortParm = String.IsNullOrEmpty(sortOrder) ? "First_Name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "OrderDate" ? "OrderDate_desc" : "OrderDate";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;

            }

            ViewBag.CurrentFilter = searchString;

            var orders = from o in db.Orders.Include(o => o.UserProfiles)
                         select o;

            if (!String.IsNullOrEmpty(searchString))
            {
                orders = orders.Where(p => p.FirstName.ToUpper().Contains(searchString.ToUpper()));

            }
            switch (sortOrder)
            {
                case "First_Name_desc":
                    orders = orders.OrderByDescending(o => o.FirstName);
                    break;
                case "OrderDate":
                    orders = orders.OrderBy(o => o.OrderDate);
                    break;
                case "OrderDate_desc":
                    orders = orders.OrderByDescending(o => o.OrderDate);
                    break;
                default:
                    orders = orders.OrderBy(o => o.FirstName);
                    break;
            }
            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(orders.ToPagedList(pageNumber, pageSize));
            //var orders = db.Orders.Include(o => o.UserProfiles);
            //return View(orders.ToList());
        }

        //
        // GET: /Order/Details/5
        [Authorize(Roles = "Admin")]
        public ActionResult Details(int id = 0)
        {
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        //


        //
        // POST: /Order/Create



        //
        // GET: /Order/Edit/5
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(int id = 0)
        {
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", order.UserId);
            return View(order);
        }

        //
        // POST: /Order/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult Edit(Order order)
        {
            if (ModelState.IsValid)
            {
                db.Entry(order).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserId = new SelectList(db.UserProfiles, "UserId", "UserName", order.UserId);
            return View(order);
        }

        //
        // GET: /Order/Delete/5
        [Authorize(Roles = "Admin")]
        public ActionResult Delete(int id = 0)
        {
            Order order = db.Orders.Find(id);
            if (order == null)
            {
                return HttpNotFound();
            }
            return View(order);
        }

        //
        // POST: /Order/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public ActionResult DeleteConfirmed(int id)
        {
            Order order = db.Orders.Find(id);
            db.Orders.Remove(order);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpPost]
        [Authorize(Roles = "Admin")]
        public ActionResult OrderFulfilled(int orderId, bool? ischecked)
        {
            Order order = db.Orders.Find(orderId);
            if (ischecked.HasValue && ischecked.Value)
            {
                order.IsFulfilled = true;
            }
            else
            {
                order.IsFulfilled = false;
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [Authorize(Roles = "Student")]
        public ActionResult StudentOrdersResult()
        {
            var orders = from o in db.Orders.Include(o => o.UserProfiles)
                         select o;
            return View(orders);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Kickoff4Kids420/Kickoff4Kids420/Controllers/SchoolController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kickoff4Kids420.Models;
using PagedList;
using PagedList.Mvc;

namespace Kickoff4Kids420.Controllers
{
    [RequireHttps]
    [Authorize(Roles = "Admin")]
    public class SchoolController : Controller
    {
        private Kickoff4KidsDb db = new Kickoff4KidsDb();

        //
        // GET: /School/

        public ActionResult Index(string currentSchool, string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "School_Name_desc" : "";
            ViewBag.CodeSortParm = sortOrder == "School_Address" ? "School_Address_desc" : "School_Address";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;

            }

            ViewBag.CurrentFilter = searchString;

            var schools = from s in db.Schools
                          select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                schools = schools.Where(s => s.SchoolName.ToUpper().Contains(searchString.ToUpper()));

            }
            switch (sortOrder)
            {
                case "School_Name_desc":
                    schools = schools.OrderByDescending(s => s.SchoolName);
                    break;
                case "School_Address":
                    schools = schools.OrderBy(s => s.SchoolAddress);
                    break;
                case "School_Address_desc":
                    schools = schools.OrderByDescending(s => s.SchoolAddress);
                    break;
                default:
                    schools = schools.OrderBy(s => s.SchoolName);
                    break;
            }

            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(schools.ToPagedList(pageNumber, pageSize));


        }

        //
        // GET: /Default1/Details/5

        public ActionResult Details(int id = 0)
        {
            School school = db.Schools.Find(id);
            if (school == null)
            {
                return HttpNotFound();
            }
            return View(school);
        }

        //
        // GET: /Default1/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Default1/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(School school)
        {
            if (ModelState.IsValid)
            {
                db.Schools.Add(school);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(school);
        }

        //
        // GET: /Default1/Edit/5

        public ActionResult Edit(int id = 0)
        {
            School school = db.Schools.Find(id);
            if (school == null)
            {
                return HttpNotFound();
            }
            return View(school);
        }

        //
        // POST: /Default1/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(School school)
        {
            if (ModelState.IsValid)
            {
                db.Entry(school).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(school);
        }

        //
        // GET: /Default1/Delete/5

        public ActionResult Delete(int id = 0)
        {
            School school = db.Schools.Find(id);
            if (school == null)
            {
                return HttpNotFound();
            }
            return View(school);
        }

        //
        // POST: /Default1/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            School school = db.Schools.Find(id);
            db.Schools.Remove(school);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Kickoff4Kids420/Kickoff4Kids420/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kickoff4Kids420.Models;

namespace Kickoff4Kids420.Controllers
{
    public class StudentController : Controller
    {
        private Kickoff4KidsDb db = new Kickoff4KidsDb();

        //
        // GET: /Student/

        public ActionResult Index()
        {
            var userprofiles = db.UserProfiles.Include(u => u.Schools);
            return View(userprofiles.ToList());
        }

        //
        // GET: /Student/Edit/5

        public ActionResult Edit(int id = 0)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            ViewBag.SchoolId = new SelectList(db.Schools, "SchoolId", "SchoolName", userprofile.SchoolId);
            return View(userprofile);
        }

        //
        // POST: /Student/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(UserProfile userprofile)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userprofile).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.SchoolId = new SelectList(db.Schools, "SchoolId", "SchoolName", userprofile.SchoolId);
            return View(userprofile);
        }

        //
        // GET: /Student/Delete/5

        public ActionResult Delete(int id = 0)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            if (userprofile == null)
            {
                return HttpNotFound();
            }
            return View(userprofile);
        }

        //
        // POST: /Student/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            UserProfile userprofile = db.UserProfiles.Find(id);
            db.UserProfiles.Remove(userprofile);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Kickoff4Kids420/Kickoff4Kids420/Views/Home/About.cshtml
@*@{
    ViewBag.Title = "About";
}*@

<hgroup class="title">
    <h1>@ViewBag.Title</h1>
</hgroup>
<center><img src="~/Images/k4k.jpg"height="300" width="600"/></center>
<article>
    <p>
        <strong><em><big>Domestic division of The Amobi Okoye Foundation </em></big></strong><br />
        Kickoff 4 Kids (K4K) was founded in 2007 by NFL defensive lineman Amobi Okoye, the Foundation’s mission is giving hope to kids, communities and building unity amongst children around the world.
        Amobi entered high school at the young age of twelve, where he distinguished himself both athletically and scholastically. He graduated from Lee High School in Huntsville, Alabama when he was only fifteen years old. Amobi’s academic prowess was evident to all. He was offered a scholarship to Harvard University, which he turned down in lieu of a football scholarship to the University of Louisville. After four football seasons and three and a half years of study, Amobi graduated with a degree in psychology; at nineteen, he also became the youngest player to ever be drafted into the NFL.
        Amobi has a passion to help children by giving them hope for the future, and letting them know that they can also achieve great things. Amobi is equally passionate about seeing communities transformed. He believes that, through partnership and collaboration, we can see the inner cities of America renewed and impoverished nations enriched.
    <p>
        The Amobi Okoye Foundation has two divisions both domestic and international: <br /> (1) Domestic Youth & Community Programs Kickoff 4 Kids (K4K) <br />(2) International Outreach Programs, based in Amobi’s home continent of Africa, Changing Africa Through Education (C.A.T.E).  Domestic programs are currently based in the inner city of Houston, Texas.  Kickoff 4 kids also have offices in Huntsville Alabama and Louisville Kentucky the place of Amobi’s high school and collegiate careers, respectively.
    </p>
    <p>
        <strong>K4K Youth & Community Programs</strong>
    <p>
        <li><strong> K4K Activities &Scholarship</strong>: Series of youth activities that uses athletics and scholarships to motivate and inspire youths, i.e. Sports Mentoring Camps, and Movies & Motivation Rallies</li>
        <li><strong> K4K House                  </strong> :   A Competition Outreach Achievement Center amongst high schools to improve school attendance, grades, good behavior, physical activity and community service</li>
        <li><strong> Tackle Hunger              </strong> :   Provides temporary sustenance for needy families <li/>
        <li><strong> Books Abroad               </strong> :   Gathers Thousands of new and used library books for the International division C.A.T.E </li>
</p>
    </p>

        To accomplish program objectives, ensure sustainable funding and garner sufficient community support, The K4K Foundation has adopted a sound strategy that incorporates an aggressive public information campaign; a Board of Directors and Councilors comprised of thoughtful leaders and key influencers, and frequent consultation with the best of professionals to ensure the integrity of all of its programs. Through a comprehensive programming model, sustainable funding and transparent reporting, The Amobi Okoye Foundation is making a difference in the lives of thousands of children and adults around the globe.   
     </p>

</article>

Kickoff4Kids420/Kickoff4Kids420/Views/Home/AdminPanel.cshtml
@{
    ViewBag.Title = "Administrator Panel";
}

<div class="breadcrumbs margin-bottom-40">
    <div class="container">
        <h1 class="pull-left">Administrator Common Functions</h1>
    </div>
</div><!--/breadcrumbs-->
<!--=== End Breadcrumbs ===-->
<!--=== Content Part ===-->
<div class="container">
    <div class="row">
        <div class="col-md-4 md-margin-bottom-50">
            <!-- Our Services -->
            <div class="servive-block servive-block-in margin-bottom-20">
                <div class="servive-block-in servive-block-colored servive-block-grey">
                    <h4>@Html.ActionLink("Add School to Program","Create","School")</h4>
                    <p><i class="icon-check"></i></p>
                    <p>Enter a new school as a participant in the Kickoff4Kids House program.</p>
                </div>
            </div> 
        </div>       
        <div class="col-md-4 md-margin-bottom-50">
            <!-- Our Services -->
            <div class="servive-block servive-block-in margin-bottom-20">
                <div class="servive-block-in servive-block-colored servive-block-green">
                    <h4>@Html.ActionLink("Add Product to Catalog", "Create", "Product")</h4>
                    <p><i class="icon-camera"></i></p>
                    <p>Enter a product that will be available for a student reward. </p>
                </div>
            </div><!--/welcome-block-->
            <!-- End Our Services -->
        </div>
        <div class="col-md-4 md-margin-bottom-50">
            <div class="servive-block servive-block-in margin-bottom-20">
                <div class="servive-block-in servive-block-colored servive-block-red">
                    <h4>@Html.ActionLink("Add Available Activity", "Create", "Activity")</h4>
                    <p><i class="icon-home"></i></p>
                    <p>Enter an activity that can be performed by students to earn points.</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 md-margin-bottom-50">
            <!-- Our Services -->
            <div class="servive-block servive-block-in margin-bottom-20">
                <div class="servive-block-in servive-block-colored servive-block-blue">
                    <h4>@Html.ActionLink("View Unfulfilled Orders", "UnFulfilledOrders", "Order")</h4>
                    <p><i class="icon-bullhorn"></i></p>
                    <p>View recent student orders that have not yet been fulfilled.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4 md-margin-bottom-50">
            <!-- Our Services -->
            <div class="servive-block servive-block-in margin-bottom-20">
                <div class="servive-block-in servive-block-colored servive-block-orange">
                    <h4>@Html.ActionLink("Modify Front Page Text", "Index", "FrontPage")</h4>
                    <p><i class="icon-gear"></i></p>
                    <p>Edit the text on the Kickoff4Kids House front page. Customize any way you like.</p>
                </div>
            </div><!--/welcome-block-->
            <!-- End Our Services -->
        </div>
        <div class="col-md-4 md-margin-bottom-50">
            <div class="servive-block servive-block-in margin-bottom-20">
                <div class="servive-block-in servive-block-colored servive-block-sea">
                    <h4>@Html.ActionLink("View Documentation", "Help", "Home")</h4>
                    <p><i class="icon-lightbulb"></i></p>
                    <p>Documentation for the common activities performed on the site.</p>
                </div>
            </div>
        </div>
    </div>
</div>

Kickoff4Kids420/Kickoff4Kids420/Views/Home/Administrator.cshtml
@{
    ViewBag.Title = "Administrator";
}

<div class="row">
    <div class="text-center">
        <p> </p>
        <img src="~/Images/KickOffForKids2.png" />
        <h2>Welcome @ViewBag.Title!</h2>
    </div>
</div>

Kickoff4Kids420/Kickoff4Kids420/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Us";
}


    @*<header>
                <h3>Phone</h3>
            </header>
            <p>
                <span class="label">Office:</span>
                <span>281-398-4201</span>
            </p>
            <p>
                <span class="label">Fax:</span>
                <span>281-398-4211</span>
            </p>
        </section>

        <section class="text-center contact">
            <header>
                <h3>Email</h3>
            </header>
            <p>
                <span class="label">Support:</span>
                <span><a href="mailto:Support@example.com">Support@example.com</a></span>
            </p>*@
    @*<p>
            <span class="label">Marketing:</span>
            <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
        </p>
        <p>
            <span class="label">General:</span>
            <span><a href="mailto:General@example.com">General@example.com</a></span>*@
    @*</p>*@
    @*</section>

        <section class="text-center contact">
            <header>
                <h3>Address</h3>
            </header>
            <p>
                1832 Snake River Road<br />
                Katy, Tx 77449
            </p>
        </section>*@

Kickoff4Kids420/Kickoff4Kids420/Views/Home/Gallery.cshtml
@{
    ViewBag.Title = "Gallery";
}
<div class="container">
    <iframe src="https://snapwidget.com/in/?u=a2lja29mZjRraWRzfGlufDMxNXwzfDN8fG5vfDV8ZmFkZUlufG9uU3RhcnR8eWVz&v=281013" allowtransparency="true" frameborder="0" scrolling="no" style="border:none; overflow:hidden; width:960px; height: 960px"></iframe>
</div>

Kickoff4Kids420/Kickoff4Kids420/Views/Home/Index.cshtml
@model Kickoff4Kids420.Models.FrontPage
@{
    ViewBag.Title = "Kickoff 4 Kids";  
}
<div class="slider-inner">
    <div id="da-slider" class="da-slider">
        <div class="da-slide">
            <h2><i> Kickoff 4 Kids</i> <br /> <i>House</i> <br /> <i>2013</i></h2>
            <div class="da-img"><img src="~/Images/k4knew.png" height="300" width="600" alt="" /></div>
        </div>
        <div class="da-slide">
            <h2><i>Earn Points</i> <br /> <i>and</i> <br /> <i>win prizes today!</i></h2>

            <div class="da-img"><img src="~/Images/apple.png" height="300" width="600" alt="image01" /></div>
        </div>
        <div class="da-slide">
            <h2><i>Get Involved</i> <br /> <i>And</i> <br /> <i>Make a Difference!</i></h2>

            <div class="da-img"><img src="/Images/students.png" height="300" width="600" alt="image01" /></div>
        </div>
        <div class="da-arrows">
            <span class="da-arrows-prev"></span>
            <span class="da-arrows-next"></span>
        </div>
    </div>
</div>
<div class="purchase">
    <div class="container">
        <div class="row">
            @if (!Request.IsAuthenticated)
{
    <div class="col-md-9">

        <span>@Model.MainText</span>
    </div>
                <div class="col-md-3">
                    <a href="/Account/Register" class="btn-buy hover-effect">@Model.MainButton</a>             
                </div>
            
                }
                @if (Request.IsAuthenticated)
            {
            <div class="col-md-12">
                <span>Welcome @User.Identity.Name! Thank your for your participation in the Kickoff 4 Kids Program!</span>
            </div>
            }
                @*<p>The Foundation’s mission is to give hope to kids, communities and to build unity amongst the children of Louisville, KY.</p>*@
            </div>
            
        </div>
    </div>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="service">
                <i class="icon-book service-icon"></i>
                <div class="desc">
                    <h4>@Model.HeaderOneText</h4>
                    <p>@Model.HeaderOneComment</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="service">
                <i class="icon-trophy service-icon"></i>
                <div class="desc">
                    <h4>@Model.HeaderTwoText</h4>
                    <p>@Model.HeaderTwoComment</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="service">
                <i class="icon-group service-icon"></i>
                <div class="desc">
                    <h4>@Model.HeaderThreeText</h4>
                    <p>@Model.HeaderThreeComment</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-md-4 md-margin-bottom-20">
                <div class="headline"><h2>Our Leaders</h2></div>
                <dl>
                    <dt>Chairman</dt>
                    <dd>Amobi Okoye</dd>
                    <dd>Augustine Okoye</dd>
                    <dd><br /></dd>
                    <dt>Pastor</dt>
                    <dd>Kenneth Tate</dd>
                    <dd><br /></dd>
                    <dt>Contributors</dt>
                    <dd>Adrian Garcia</dd>
                    <dd>Don Elder</dd>
                    <dd>Dr. Imo Aisiku</dd>
                    <dd>Judge Jimmy Thornton</dd>
                </dl>
            </div>
            <div class="col-md-4 md-margin-bottom-20">
                <div class="headline"><h2>About The Program</h2></div>
                <p>Kickoff 4 Kids is a program designed to get kids involved at school while having fun at the same time.
                    Participating students will be able to earn points by completing agreed upon activities. These points
                    can then be redeemed to purchase awards. </p><p>Through this system we hope to effect positive change within the community while making a 
                                                                     lasting impact on the lives of the youth of Louisville, KY. </p>
            </div>
                       
            <div class="col-md-4 md-margin-bottom-20">
                <div class="headline"><h2>Contact Us</h2></div>
                <address class="md-margin-bottom-40">
                    1832 Snake River Road <br />
                    Katy Tx 77449 <br />
                    Phone:  281-398-4201 <br />
                    Fax: 281-398-4211 <br />
                    Email: Info@amobiokoyefoundation.org
                </address>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    @Scripts.Render("~/bundles/index")
}

Kickoff4Kids420/Kickoff4Kids420/Views/Home/Student.cshtml
@{
    ViewBag.Title = "Student";
}

<div class="row">
    <div class="text-center">
        <p> </p>
        <img src="~/Images/KickOffForKids2.png" />
        <h2>Welcome @ViewBag.Title!</h2>
    </div>
</div>